---

STORAGE_REGION: ""
STORAGE_ENDPOINT: ""
STORAGE_ACCESS_KEY: ""
STORAGE_ACCESS_SECRET: ""
STORAGE_BUCKET: ""
POSTGRES_DB: ""
POSTGRES_USER: ""
POSTGRES_PASSWORD: ""
POSTGRES_HOST: ""
POSTGRES_PORT: ""
ELASTICSEARCH_HOST: ""
ELASTICSEARCH_INDEX: ""
DEBUG: "0"

CONFIGDIR: "/etc/gazette-content-extraction"
CONTAINER_IMAGE: "docker.io/serenata/querido-diario-data-processing:latest"
CONTAINER_NAME: "gazette-content-extraction"
CONTAINER_CPU: 1
CONTAINER_MEMORY: "128m"

TIMER:
  ONCALENDAR: "daily"

APACHE_TIKA_SERVER: "http://localhost:9998"
APACHE_TIKA_CONTAINER_IMAGE: "docker.io/serenata/querido-diario-apache-tika-server:latest"
APACHE_TIKA_CONTAINER_NAME: "querido-diario-apache-tika-server"

POD_NAME: "querido-diario"

QUERIDO_DIARIO_FILES_ENDPOINT: ""
