---
- name: create data directory
  file:
      path: "{{ host_data_path }}"
      state: directory
      owner: "spider"
      group: "spider"

- name: create data directory for each city
  file:
      path: "{{ host_data_path }}/{{ item }}"
      state: directory
      owner: "spider"
      group: "spider"
  loop: "{{cities}}"
