---
- name: find files to delete
  find:
      paths: "/etc/systemd/system/"
      patterns: "spider@*"
      file_type: any
  register: files_to_delete

- name: delete old service and timer files
  file:
      path: "{{ item.path }}"
      state: absent
  with_items: "{{ files_to_delete.files }}"
