---
- name: install service file
  template:
      src: spider.service.j2
      dest: "/etc/systemd/system/spider@.service"

- name: create timer for the spiders
  template:
      src: spider.timer.j2
      dest: "/etc/systemd/system/spider@.timer"

- name: create cities spider
  file:
      src: "/etc/systemd/system/spider@.service"
      dest: "/etc/systemd/system/spider@{{item}}.service"
      state: link
  loop: "{{cities}}"

- name: create spider timers
  file:
      src: "/etc/systemd/system/spider@.timer"
      dest: "/etc/systemd/system/spider@{{item}}.timer"
      state: link
  loop: "{{cities}}"
