---
- name: install the service to download container image
  template:
      src: container_image_puller.service.j2
      dest: "/etc/systemd/system/container_image_puller.service"

- name: create timer to trigger the container image download
  template:
      src: container_image_puller.timer.j2
      dest: "/etc/systemd/system/container_image_puller.timer"
