---
- name: create spider user group
  group:
      name: spider
      gid: 1000

- name: create spider user
  user:
      name: spider
      uid: 1000
      group: spider

- name: create /etc/diario
  file:
      path: "{{ diario_configdir }}"
      state: directory

- name: create env var file
  template:
      src: env.j2
      dest: "{{ diario_configdir }}/env"

- import_tasks: create_data_directories.yaml

- import_tasks: delete_systemd_service_files.yaml

- import_tasks: install_base_service_files.yaml

- import_tasks: install_image_puller_service.yaml

- name: reload systemd daemon
  systemd:
    daemon_reload: yes

- import_tasks: start_timers.yaml


