---
- name: start timer for the spiders
  systemd:
      name: "spider@{{item}}.timer"
      enabled: yes
      state: started
  loop: "{{cities}}"

- name: start timer to download container image
  systemd:
      name: "container_image_puller.timer"
      enabled: yes
      state: started
