---
- name: install service to run content extractor
  template:
      src: gazette_content_extraction.service.j2
      dest: "/etc/systemd/system/gazette_content_extraction.service"

- name: create timer for trigger the content extractor
  template:
      src: gazette_content_extraction.timer.j2
      dest: "/etc/systemd/system/gazette_content_extraction.timer"

- name: install service to run apache tika server
  template:
      src: querido-diario-apache_tika_server.service.j2
      dest: "/etc/systemd/system/querido-diario-apache_tika_server.service"
