---
- debug:
    msg: "Target distribution: {{ ansible_distribution }}"

- debug:
    msg: "Target distribution: {{ ansible_facts['ansible_distribution_version'] }}"

- name: Upgrade everything
  apt: 
    upgrade: yes

- name: Update everything
  apt: 
    name: "*"
    state: latest
