---
container_image: "docker.io/serenata/diario-oficial:latest"
host_data_path: "/var/diario/data"
diario_configdir: "/etc/diario"
containeruser: "gazette"

postgres:
    username : "gazette"
    password : "password"
    host : "localhost"
    port : 5432
    database : "gazette"
