---
container_image: "docker.io/serenata/diario-oficial:latest"
host_data_path: "/var/diario/data"
diario_configdir: "/etc/diario"
containeruser: "gazette"
timer:
    oncalendar: "daily"
    randomizeddelaysec: 43200

ITEM_PIPELINES: "{\"gazette.pipelines.GazetteDateFilteringPipeline\": 50, \"gazette.pipelines.QueridoDiarioFilesPipeline\": 100,}"
SPIDER_MIDDLEWARES: "{\"scrapy_deltafetch.DeltaFetch\": 100}"

DELTAFETCH_ENABLED:  False
DELTAFETCH_DIR: "/mnt/data/deltafetch"

ELASTICSEARCH_HOSTS: ""
ELASTICSEARCH_INDEX: ""

DELETE_FILE_AFTER_EXTRACT_TEXT: False

#Digital Ocean spaces config
FILES_STORE: "/mnt/data/"
AWS_ACCESS_KEY_ID: ""
AWS_SECRET_ACCESS_KEY: ""
AWS_ENDPOINT_URL: ""
AWS_REGION_NAME: ""

postgres:
    username : "gazette"
    password : "password"
    host : "localhost"
    port : 5432
    database : "gazette"
    sslmode : "require"

cities:
    - al_maceio
    - am_manaus
    - ba_feira_de_santana
    - ba_salvador
    - ce_fortaleza
    - es_associacao_municipios
    - go_aparecida_de_goiania
    - go_goiania
    - mg_uberaba
    - ms_campo_grande
    - pr_cascavel
    - pr_curitiba
    - pr_foz_do_iguacu
    - pr_londrina
    - pr_maringa
    - pr_ponta_grossa
    - rj_rio_de_janeiro
    - ro_porto_velho
    - rr_boa_vista
    - rs_caxias_do_sul
    - rs_gravatai
    - rs_porto_alegre
    - sc_abdon_batista
    - sc_agrolandia
    - sc_agronomica
    - sc_agua_doce
    - sc_aguas_de_chapeco
    - sc_aguas_frias
    - sc_aguas_mornas
    - sc_alfredo_wagner
    - sc_alto_bela_vista
    - sc_anchieta
    - sc_angelina
    - sc_anita_garibaldi
    - sc_anitapolis
    - sc_antonio_carlos
    - sc_apiuna
    - sc_arabuta
    - sc_arroio_trinta
    - sc_arvoredo
    - sc_ascurra
    - sc_atalanta
    - sc_aurora
    - sc_balneario_arroio_do_silva
    - sc_balneario_camboriu
    - sc_balneario_gaivota
    - sc_balneario_picarras
    - sc_balneario_rincao
    - sc_bandeirante
    - sc_barra_bonita
    - sc_barra_velha
    - sc_bela_vista_do_toldo
    - sc_belmonte
    - sc_benedito_novo
    - sc_biguacu
    - sc_blumenau
    - sc_bom_jardim_da_serra
    - sc_bom_jesus
    - sc_bom_jesus_do_oeste
    - sc_bom_retiro
    - sc_botuvera
    - sc_braco_do_norte
    - sc_braco_do_trombudo
    - sc_brunopolis
    - sc_brusque
    - sc_cacador
    - sc_caibi
    - sc_camboriu
    - sc_campo_alegre
    - sc_campo_ere
    - sc_campos_novos
    - sc_canelinha
    - sc_canoinhas
    - sc_capao_alto
    - sc_capinzal
    - sc_catanduvas
    - sc_caxambu_do_sul
    - sc_celso_ramos
    - sc_cerro_negro
    - sc_chapadao_do_lageado
    - sc_chapeco
    - sc_cocal_do_sul
    - sc_concordia
    - sc_cordilheira_alta
    - sc_coronel_freitas
    - sc_coronel_martins
    - sc_correia_pinto
    - sc_corupa
    - sc_criciuma
    - sc_cunha_pora
    - sc_cunhatai
    - sc_curitibanos
    - sc_descanso
    - sc_dionisio_cerqueira
    - sc_dona_emma
    - sc_doutor_pedrinho
    - sc_entre_rios
    - sc_ermo
    - sc_erval_velho
    - sc_faxinal_dos_guedes
    - sc_flor_do_sertao
    - sc_florianopolis
    - sc_formosa_do_sul
    - sc_forquilhinha
    - sc_fraiburgo
    - sc_frei_rogerio
    - sc_galvao
    - sc_garopaba
    - sc_garuva
    - sc_gaspar
    - sc_governador_celso_ramos
    - sc_grao_para
    - sc_gravatal
    - sc_guabiruba
    - sc_guaraciaba
    - sc_guaramirim
    - sc_guaruja_do_sul
    - sc_guatambu
    - sc_herval_doeste
    - sc_ibiam
    - sc_ibicare
    - sc_ibirama
    - sc_ilhota
    - sc_imarui
    - sc_imbituba
    - sc_imbuia
    - sc_indaial
    - sc_iomere
    - sc_ipira
    - sc_ipora_do_oeste
    - sc_ipuacu
    - sc_ipumirim
    - sc_iraceminha
    - sc_irani
    - sc_irati
    - sc_irineopolis
    - sc_ita
    - sc_itaiopolis
    - sc_itajai
    - sc_itapema
    - sc_itapiranga
    - sc_itapoa
    - sc_ituporanga
    - sc_jabora
    - sc_jacinto_machado
    - sc_jaguaruna
    - sc_jaragua_do_sul
    - sc_jardinopolis
    - sc_joacaba
    - sc_jose_boiteux
    - sc_jupia
    - sc_lacerdopolis
    - sc_lages
    - sc_laguna
    - sc_lajeado_grande
    - sc_lauro_muller
    - sc_lebon_regis
    - sc_leoberto_leal
    - sc_lindoia_do_sul
    - sc_lontras
    - sc_luiz_alves
    - sc_luzerna
    - sc_macieira
    - sc_mafra
    - sc_major_vieira
    - sc_maracaja
    - sc_maravilha
    - sc_marema
    - sc_massaranduba
    - sc_matos_costa
    - sc_meleiro
    - sc_mirim_doce
    - sc_modelo
    - sc_mondai
    - sc_monte_carlo
    - sc_monte_castelo
    - sc_morro_da_fumaca
    - sc_morro_grande
    - sc_navegantes
    - sc_nova_erechim
    - sc_nova_itaberaba
    - sc_nova_trento
    - sc_nova_veneza
    - sc_novo_horizonte
    - sc_orleans
    - sc_otacilio_costa
    - sc_ouro
    - sc_ouro_verde
    - sc_paial
    - sc_palhoca
    - sc_palma_sola
    - sc_palmeira
    - sc_palmitos
    - sc_papanduva
    - sc_paraiso
    - sc_passo_de_torres
    - sc_passos_maia
    - sc_paulo_lopes
    - sc_pedras_grandes
    - sc_penha
    - sc_peritiba
    - sc_pescaria_brava
    - sc_petrolandia
    - sc_pinhalzinho
    - sc_pinheiro_preto
    - sc_piratuba
    - sc_planalto_alegre
    - sc_pomerode
    - sc_ponte_alta_do_norte
    - sc_ponte_serrada
    - sc_porto_belo
    - sc_porto_uniao
    - sc_pouso_redondo
    - sc_praia_grande
    - sc_presidente_castello_branco
    - sc_presidente_getulio
    - sc_presidente_nereu
    - sc_princesa
    - sc_quilombo
    - sc_rancho_queimado
    - sc_rio_das_antas
    - sc_rio_do_campo
    - sc_rio_do_oeste
    - sc_rio_do_sul
    - sc_rio_dos_cedros
    - sc_rio_fortuna
    - sc_rio_negrinho
    - sc_rio_rufino
    - sc_rodeio
    - sc_romelandia
    - sc_saltinho
    - sc_salto_veloso
    - sc_santa_cecilia
    - sc_santa_helena
    - sc_santa_rosa_de_lima
    - sc_santa_rosa_do_sul
    - sc_santa_terezinha_do_progresso
    - sc_santiago_do_sul
    - sc_santo_amaro_da_imperatriz
    - sc_sao_bento_do_sul
    - sc_sao_bernardino
    - sc_sao_bonifacio
    - sc_sao_carlos
    - sc_sao_cristovao_do_sul
    - sc_sao_domingos
    - sc_sao_francisco_do_sul
    - sc_sao_joao_batista
    - sc_sao_joao_do_oeste
    - sc_sao_joao_do_sul
    - sc_sao_joaquim
    - sc_sao_jose
    - sc_sao_jose_do_cedro
    - sc_sao_jose_do_cerrito
    - sc_sao_lourenco_do_oeste
    - sc_sao_miguel_da_boa_vista
    - sc_sao_miguel_do_oeste
    - sc_sao_pedro_de_alcantara
    - sc_saudades
    - sc_schroeder
    - sc_seara
    - sc_serra_alta
    - sc_sideropolis
    - sc_sombrio
    - sc_sul_brasil
    - sc_tangara
    - sc_tigrinhos
    - sc_tijucas
    - sc_timbe_do_sul
    - sc_timbo
    - sc_timbo_grande
    - sc_tres_barras
    - sc_treviso
    - sc_treze_de_maio
    - sc_treze_tilias
    - sc_trombudo_central
    - sc_tubarao
    - sc_tunapolis
    - sc_turvo
    - sc_uniao_do_oeste
    - sc_urubici
    - sc_urupema
    - sc_urussanga
    - sc_vargeao
    - sc_vargem
    - sc_vargem_bonita
    - sc_vidal_ramos
    - sc_videira
    - sc_vitor_meireles
    - sc_witmarsum
    - sc_xanxere
    - sc_xavantina
    - sc_xaxim
    - sc_zortea
    - sp_campinas
    - sp_franca
    - sp_guaruja
    - sp_guarulhos
    - sp_jundiai
    - sp_santos
    - sp_sao_jose_dos_campos
    - to_araguaina
    - to_palmas
